### ISSUE TITLE
Change the content of navbar and title from header section.

### ISSUE THREAD

**Issue by MuktaTiwari** [MuktaTiwari/Portfolio_Task1#2]
1. Change title v-Indus to portfolio
2. change the  logo "v-indus" to Portfolio
3. in the navbar Home, About, Project, Skills, and Contact are required, Remove other features.
4. change the "Get a help" title of a button to "Github Profile" and after clicking on the button github profile should open. github
 link: https://github.com/MuktaTiwari

**Comment by shubham-ghaturle01** [comment]
Hi @MuktaTiwari ,

I noticed a few things in the portfolio website that need fixing. Would you like me to go ahead and fix them for you? Here’s a quick overview of what needs to be updated:

Change the navbar title to "Portfolio."
Update the navbar links (Home, About, Project, Skills, Contact).
Update the button text to "Github Profile" and make it open the GitHub profile link.
Let me know if it's okay for me to handle these changes.

Thanks!
Shubham Ghaturle

**Comment by MuktaTiwari** [comment]
Hii @Shubhuscode 
ok, you can handle these things.
