### ISSUE TITLE
Fix the paragraph of home page

### ISSUE THREAD

**Issue by MuktaTiwari** [MuktaTiwari/Portfolio_Task1#3]
1. change "We are product designers" to GET(Graduate Engineer Training). from the main section.
2. change the paragraph from the main section and add, "As a graduate engineer in Information Technology, I specialize in developing innovative solutions through a blend of technical expertise and creativity. My experience with Java, Spring, Hibernate, and MySQL has enabled me to design applications. I am passionate about contributing to the future of technology by solving real-world challenges and delivering impactful results." instead of Lorem text.
3. Change the title of the button "Learn more" to "Look at my CV" and link the PDF file of the resume to that button.
[Manimukta_Tiwari_pinnacel (1).pdf](https://github.com/user-attachments/files/18257900/Manimukta_Tiwari_pinnacel.1.pdf)

**Comment by Saifkhan-rkp** [comment]
Hey @MuktaTiwari , I am keen to work on addressing this issue. give me a little detail on how i use attached pdf.
should set it available to download or set it to view on same page like we use iframes?

**Comment by MuktaTiwari** [comment]
Hii @Saifkhan-rkp 
The pdf should open in a new tab.
