### ISSUE TITLE
fix heading in about section

### ISSUE THREAD

**Issue by MuktaTiwari** [MuktaTiwari/Portfolio_Task1#4]
1. change the heading "Why Our company" to "About Me" from the About section.
2. Remove the whole ul tag from the About section.
3. change the paragraph content in the About section. instead of Lorem sentence add "I am Manimukta Tiwari, a Graduate Engineer Training with a strong foundation in Information Technology, graduated from Ramdeobaba College of Engineering and Management. With 6 months of hands-on experience as a Java Developer at Oakland Systems, I have worked with cutting-edge technologies like Java, Spring, Hibernate, JSP, MySQL, and more. developing user-friendly solutions, aiming to deliver impactful and innovative software. Currently, I am seeking opportunities to leverage my skills and contribute to meaningful projects in the tech industry. Let's build something amazing together!"

**Comment by keshav-09** [comment]
Hi @MuktaTiwari , I would like to take up this issue. If you permit, please comment Accordingly, I will start working on it.

**Comment by MuktaTiwari** [comment]
yes, you can start your work.
