### ISSUE TITLE
Change the service section to project section

### ISSUE THREAD

**Issue by MuktaTiwari** [MuktaTiwari/Portfolio_Task1#5]
Instead of a service card add the projects, description, and GitHub link to that card. Add two projects and remove the other cards 
Add the link to that Arror icon that is present on the card.

first Project : 
		 	     Name: Blog_Site
			     description: Crafted with HTML, CSS, and JS, Blog_Site is your 
                             gateway to captivating stories and dynamic content.
			     Provide link in button format: 
                             https://muktatiwari.github.io/Blog_site/ 
Second project : 
			Name: Shop website
			 description: Where shopping meets convenience and style! We're 
                         excited to present our E-Commerce Shop, a digital haven curated 
                         for seamless browsing and effortless shopping. With a user- 
                         friendly interface and a vast array of products, we invite you to 
                         explore the world of online retail right from the comfort of your 
                         device.
			 Provide link in button format : 
                         https://muktatiwari.github.io/shop_website/

**Comment by arshad-khan1** [comment]
Hi @MuktaTiwari,
I would like to work on this issue.
Please let me know if someone else is working on it or should I start woking on it

Thank you,
Arshad Khan

**Comment by MuktaTiwari** [comment]
Hii @arshad-khan1 
No one is working on this.
you can start working on this task.
Please feel free to ask me if you have any questions.

**Comment by MuktaTiwari** [comment]
Hii @arshad-khan1 
is there any update about this issue?
And let me know if any doubt you have.
