### ISSUE TITLE
Change Features section with skills section.

### ISSUE THREAD

**Issue by MuktaTiwari** [MuktaTiwari/Portfolio_Task1#6]
1. Change the heading "Our Features" to Skills from the features section.

2. Add the skills in the feature sections like Java, HTML, CSS, MySQL, spring, hibernate, and javascript in a systematic way 
3. Remove the previous code and add a skill with some progress bar or you can also use the card

**Comment by kambleaishwarya** [comment]
Hi mukta, I would like to take up this issue. If you permit, please comment Accordingly, I will start working on it.

**Comment by MuktaTiwari** [comment]
Hii @kambleaishwarya 
yes, you can start your implementation.

**Comment by kambleaishwarya** [comment]
Hi Mukta, I have made the changes as per your requirements. Please check them once,
![Screenshot from 2024-12-28 20-59-03](https://github.com/user-attachments/assets/17175bd1-3717-4811-94ea-50e1c98c29ec)
and let me know. I have attached a screenshot for your reference.

**Comment by MuktaTiwari** [comment]
ok this design is fine you can commit this

**Comment by kambleaishwarya** [comment]
okay mukta!

**Comment by kambleaishwarya** [comment]
hii mukta i have created pull request again please check out
