### ISSUE TITLE
Remove non working content from the contact section

### ISSUE THREAD

**Issue by MuktaTiwari** [MuktaTiwari/Portfolio_Task1#8]
1. Remove Our Services
2. Change the linking from our links. For example, clicking on the home page 
 should go to the home page.
4. Remove the "Other Links" section.
5. In contact add email and remove other things. 
7. remove footer-bottom div
8. you can add a small form in the contact section with Name email and message fields

**Comment by keshav-09** [comment]
Hi @MuktaTiwari ,

Is anyone else working on this task, or should I start working on it?

Please let me know.

**Comment by MuktaTiwari** [comment]
Hii @keshav-09 
No one is working on this.
you can start working on this.
please feel free to ask any doubts.

**Comment by keshav-09** [comment]
Okay.
Thank you!

**Comment by keshav-09** [comment]
@MuktaTiwari 
Is i have add any alert message when some one is submit without any information

**Comment by MuktaTiwari** [comment]
yes you can add some alerts when someone is trying to submit the message without fill-up the form
![Screenshot from 2024-12-29 18-47-25](https://github.com/user-attachments/assets/db243ecc-d67b-441b-a988-c5795ffa7716)

some thing like this

**Comment by keshav-09** [comment]
Okay @MuktaTiwari 
Working on it!

**Comment by keshav-09** [comment]
![image](https://github.com/user-attachments/assets/6515e7b1-a4aa-4ae7-8b76-0c2d07947d88)
Is this correct? @MuktaTiwari

**Comment by MuktaTiwari** [comment]
yes this is fine

**Comment by keshav-09** [comment]
Okay
